ontact_links:
  - name: [GERMAN] Help & Support Telegram Group
    url: https://t.me/womo_LIN
    about: Need help with installation or usage? Please join our Telegram community
  - name: [ENGLISH] Help & Support Telegram Group
    url: https://t.me/womolin_en
    about: Need help with installation or usage? Please join our Telegram community
